/* This file is automatically generated.
   It defines macros to allow user program to find the shared
   library files which come as part of GNU libc.  */
#ifndef __GNU_LIB_NAMES_H
#define __GNU_LIB_NAMES_H	1

#include <bits/wordsize.h>

#if __WORDSIZE == 32
# define LD_NACL_X86_32_SO              "ld-nacl-x86-32.so.11835d88"
# define LD_SO                          "ld-nacl-x86-32.so.11835d88"
# define LIBANL_SO                      "libanl.so.11835d88"
# define LIBBROKENLOCALE_SO             "libBrokenLocale.so.11835d88"
# define LIBCIDN_SO                     "libcidn.so.11835d88"
# define LIBCRYPT_SO                    "libcrypt.so.11835d88"
# define LIBC_SO                        "libc.so.11835d88"
# define LIBDL_SO                       "libdl.so.11835d88"
# define LIBM_SO                        "libm.so.11835d88"
# define LIBNSL_SO                      "libnsl.so.11835d88"
# define LIBNSS_COMPAT_SO               "libnss_compat.so.11835d88"
# define LIBNSS_DNS_SO                  "libnss_dns.so.11835d88"
# define LIBNSS_FILES_SO                "libnss_files.so.11835d88"
# define LIBNSS_HESIOD_SO               "libnss_hesiod.so.11835d88"
# define LIBNSS_LDAP_SO                 "libnss_ldap.so.11835d88"
# define LIBNSS_NISPLUS_SO              "libnss_nisplus.so.11835d88"
# define LIBNSS_NIS_SO                  "libnss_nis.so.11835d88"
# define LIBPTHREAD_SO                  "libpthread.so.11835d88"
# define LIBRESOLV_SO                   "libresolv.so.11835d88"
# define LIBRT_SO                       "librt.so.11835d88"
# define LIBTHREAD_DB_SO                "libthread_db.so.11835d88"
# define LIBUTIL_SO                     "libutil.so.11835d88"
#else
# define LD_NACL_X86_64_SO              "ld-nacl-x86-64.so.11835d88"
# define LD_SO                          "ld-nacl-x86-64.so.11835d88"
# define LIBANL_SO                      "libanl.so.11835d88"
# define LIBBROKENLOCALE_SO             "libBrokenLocale.so.11835d88"
# define LIBCIDN_SO                     "libcidn.so.11835d88"
# define LIBCRYPT_SO                    "libcrypt.so.11835d88"
# define LIBC_SO                        "libc.so.11835d88"
# define LIBDL_SO                       "libdl.so.11835d88"
# define LIBM_SO                        "libm.so.11835d88"
# define LIBNSL_SO                      "libnsl.so.11835d88"
# define LIBNSS_COMPAT_SO               "libnss_compat.so.11835d88"
# define LIBNSS_DNS_SO                  "libnss_dns.so.11835d88"
# define LIBNSS_FILES_SO                "libnss_files.so.11835d88"
# define LIBNSS_HESIOD_SO               "libnss_hesiod.so.11835d88"
# define LIBNSS_LDAP_SO                 "libnss_ldap.so.11835d88"
# define LIBNSS_NISPLUS_SO              "libnss_nisplus.so.11835d88"
# define LIBNSS_NIS_SO                  "libnss_nis.so.11835d88"
# define LIBPTHREAD_SO                  "libpthread.so.11835d88"
# define LIBRESOLV_SO                   "libresolv.so.11835d88"
# define LIBRT_SO                       "librt.so.11835d88"
# define LIBTHREAD_DB_SO                "libthread_db.so.11835d88"
# define LIBUTIL_SO                     "libutil.so.11835d88"
#endif

#endif	/* gnu/lib-names.h */
