/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "42a741a2145c825b909327a520ebbb9b712e8fff"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
