/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "c388689a0752aa4d2c1e0b559dc6cf40b57ff012"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
