/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "70a12a07d90c157e87ffbc0caf9857c0bf9d691e"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
